# TP 0

## 0bjectifs

* Comprendre les bases de la programmation Python :
* Variables, types de données, listes, ensembles et tuples.
* Expressions conditionnelles et boucles
* Trier
* Dictionnaire
* Fichiers et interaction avec les utilisateurs
* Numpy

## Exercice 1

1\. Commentaires


In [1]:
# Ceci est un commentaire
print("Bonjour")

Bonjour


2\. Variables



In [2]:
# une variable
message = "le monde!"
print(message)

le monde!


In [3]:
a = 10
b = 20
c = a + b
print(c)

30


In [4]:
# nombres réels
pi = 3.14
print(pi)

3.14


In [5]:
# types de donnés
message1 = "Bonjour"
a = 12
pi = 3.14
print(type(message1))
print(type(a))
print(type(pi))

<class 'str'>
<class 'int'>
<class 'float'>


3\. Concaténation de deux chaînes de caractères



In [6]:
# Concaténation de deux chaînes de caractères
message = "le monde!"
print("Bonjour" + message)

Bonjourle monde!


In [7]:
# Concaténation de deux chaînes de caractères
message1 = "Bonjour "
message2 = "le monde!"
print(message1 + message2)

Bonjour le monde!


In [9]:
# concaténation de deux variables de types de données différents
# opération + sur deux types de données différents

# Supprimer le commentaire ci-dessous et lancer le code
message1 = "Bonjour en Python"
a = 3
print(message1 + a)

TypeError: can only concatenate str (not "int") to str

Pourquoi cette erreur ? Dans le code suivant, nous corrigeons cette erreur.

In [10]:
# solution de concaténation entre deux variables de types de données différents
message1 = "Bonjour en Python "
a = 3
print(message1 + str(a))

Bonjour en Python 3


4\. Listes

In [11]:
a = [10, 20, 30, 40, 50]
print(a)

[10, 20, 30, 40, 50]


In [12]:
a = [10, 20, 30, 40, 50]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

10
20
30
40
50


In [ ]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]
# print(a[8])

Nous essayons d'accéder à un élément à un index qui n'existe pas

In [ ]:
message1 = "Bonjour en Python "
print(message1[0])
print(message1[1])
print(message1[2])
print(message1[3])
print(message1[4])
print(message1[5])
print(message1[6])
print(message1[7])

Le code ci-dessus affiche les différents caractères de la chaîne (ou liste de caractères).
Nous allons maintenant obtenir la longueur de cette chaîne.

In [ ]:
message1 = "Bonjour en Python "
print(len(message1))

Nous allons maintenant créer une liste d'entiers

In [ ]:
a = [10, 20, 30, 40, 50]
print(len(a))

In [ ]:
a = [10, 20, 30, 40, 50]

# ajouter un nouveau numéro à la fin de la liste
a.append(60)
print(a)

In [ ]:
a = [10, 20, 30, 40, 50]

# modifier un numéro à un index donné
a[0] = 0
print(a)

In [ ]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]

# a[6] = 20
print(a)

Pourquoi cette erreur? Nous modifions un élément à un indice inexistant.

In [ ]:
a = [10, 20, 30, 40, 50]

# l'insertion d'un élément à un index particulier modifiera la liste
a.insert(0, 0)
print(a)
print(len(a))

In [ ]:
a = [10, 20, 30, 40, 50]
a.insert(6, 60)
print(a)
print(len(a))

In [ ]:
a = [10, 20, 30, 40, 50]

# Nous allons maintenant essayer d'insérer un nombre à un index plus grand que la longueur
# de la liste. Nous veillerons à ce qu'il n'y ait pas d'erreur et le nouveau numéro
# est ajouté à la fin de la liste
a.insert(10, 60)
print(a)
print(len(a))

5\. Tuples (non-modifiable lists)



In [ ]:
a = (10, 20, 30, 40, 50)
print(a)

In [ ]:
a = (10, 20, 30, 40, 50)
print(a[0])

In [ ]:
a = (10, 20, 30, 40, 50)


# Nous essayons maintenant de modifier un tuple
# Décommentez le code ci-dessous et lancez le code
# Un tupe est une liste non modifiable

# a[0] = 0
print(a)

6\. Sets



In [ ]:
# Un ensemble(Set) est une collection d'éléments distincts

a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)

In [ ]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(10)
print(a)

In [ ]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(60)
print(a)

In [ ]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.remove(40)
print(a)

Nous allons maintenant essayer différents types de données avec les chiffres et afficher le résultat.

In [ ]:
# set
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)
print(type(a))

# tuple
b = (10, 20, 30, 40, 50, 10, 20, 30, 40, 50)
print(b)
print(type(b))

# list
c = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(c)
print(type(c))

## Exercice 2

1\. Expressions conditionnelles


In [13]:
a = 12
if a % 2 == 0:
    print(a, " is divisible by 2")
else:
    print(a, " is not divisible by 2")

12  is divisible by 2


In [ ]:
lang = "Français"
if lang == "Français":
    print("Bonjour le monde!")
else:
    print("Hello World!")

2\. Boucles

Les boucles peuvent également être utilisées pour accéder aux éléments de différents indices.

In [ ]:
# liste
for i in [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]:
    print(i)

In [ ]:
# tuples
for i in (10, 20, 30, 40, 50, 10, 20, 30, 40, 50):
    print(i)

In [ ]:
# set
for i in {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}:
    print(i)

2\. Limites



In [ ]:
for i in range(0, 10):
    print(i)

In [ ]:
for i in range(0, 10, 2):
    print(i)

In [14]:
# print() par défaut affiche le message suivi d'une nouvelle ligne
# Mais vous pouvez changer son comportement

for i in range(0, 10, 2):
    print(i, end=" ")

0 2 4 6 8 

In [ ]:
for i in range(10, 0, -2):
    print(i)

In [ ]:
for i in range(10, 0):
    print(i)

split(): La fonction peut être utilisée pour séparer une chaîne de caractères en utilisant 
un délimiteur spécifié. Par défaut, le délimiteur est un espace blanc.

In [15]:
for i in "Bonjour,le,monde!".split():
    print(i)

Bonjour,le,monde!


In [16]:
for i in "Bonjour,le,monde!".split(","):
    print(i)

Bonjour
le
monde!


Write a program in Python to display the following output

  
 1
 
 12
 
 123
 
 1234
 
 12345
 
 123456
 
 1234567
 
 12345678

In [19]:
for i in range(8):
    print("".join([f"{j+1}" for j in range(i+1)]))

1
12
123
1234
12345
123456
1234567
12345678


## Exercice 3

1\. Tri



In [ ]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort()
print(num)

2\. Tri (ordre décroissant)



In [ ]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort(reverse=True)
print(num)

3\. minimum



In [ ]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(min(num))

4\. maximum



In [ ]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(max(num))

5\. sorted()

Vous pouvez utiliser cette fonction si vous ne souhaitez pas modifier votre liste initiale par un tri.

In [20]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
tri = sorted(num, reverse=True)
print(num)
print(tri)

[70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
[80, 70, 70, 60, 50, 50, 30, 20, 20, 10]


In [21]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]

# sélectionner les cinq premiers numéros
tri = sorted(num, reverse=True)[:5]
print(tri)

[80, 70, 70, 60, 50]


Modifiez le code donné ci-dessous pour afficher les cinq plus grands numéros uniques.


In [24]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]

# sélectionner les cinq premiers numéros uniques
tri = sorted(num, reverse=True)[:5]
# On utilise un SET pour supprimer les doublons dans un élément itérable
tri = set(tri)
print(*tri)

80 50 60 70


## Exercice 4

1\. Dictionnaire



In [25]:
a = {"contente": 12, "content": 12, "triste": 2}
print(a)
print(type(a))

{'contente': 12, 'content': 12, 'triste': 2}
<class 'dict'>


In [26]:
a = {"contente": 12, "content": 12, "triste": 2}
for key in a:
    print("la phrase ", key, " apparait ", a[key], " fois")

la phrase  contente  apparait  12  fois
la phrase  content  apparait  12  fois
la phrase  triste  apparait  2  fois


In [ ]:
a = {"contente": 12, "content": 12, "triste": 2}
for key, value in a.items():
    print("la phrase ", key, " apparait ", value, " fois")

In [ ]:
a = {"contente": 12, "content": 12, "triste": 2}
a["joie"] = 10
print(a)

In [ ]:
a = {"contente": 12, "content": 12, "triste": 2}
del a["triste"]
print(a)

In [ ]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
print(sorted(mots))

In [ ]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(mots_tuple)

2\. itemgetter

In [27]:
from operator import itemgetter

mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(sorted(mots_tuple, key=itemgetter(1)))

[('triste', 2), ('joie', 10), ('contente', 12), ('content', 12)]


3\. Interaction with user

In [ ]:
# nom = input("Quel est votre nom?")
# print(nom)

In [ ]:
# age = input("Quel est votre âge? ")
# print(age)
# print(type(age))

In [ ]:
# age = input("Quel est votre âge? ")
# age = int(age)
# print(age)
# print(type(age))

**Question:** Ecrire un programme en Python qui interagit avec l'utilisateur pour
obtenir les informations suivantes de 5 étudiants :

- Nom de l'étudiant
- Âge
- Grades en 5 modules

Une fois les informations obtenues pour les cinq étudiants, calculez
et afficher les valeurs suivantes pour chaque module :

- note moyenne
- note maximale
- note minimale

In [1]:
NBR_ELEVES = 3

class Etudiant():
    def __init__(self, nom, age, notes):
        self.nom = nom
        self.age = age
        self.notes = notes
        self.moyenne = 0

eleves = []

for _ in range(NBR_ELEVES):
    nom = input("Entrer le nom de l'élève: ")
    age = int(input("Entrer l'age de l'élève: "))
    notes = [int(input("Entrer une note : ")) for _ in range(3)]
    eleves.append(Etudiant(nom, age, notes))

# Calcule de la moyenne, de la meilleure note et de la moins bonne note

moyenne = 0
note_min = 21
note_max = 0

for eleve in eleves:

    # Scrap de toutes les notes pour la pire et la meilleure
    for note in eleve.notes:
        # Meilleure note
        if note > note_max :
            note_max = note

        # Pire note
        if note < note_min:
            note_min = note

    moyenne += sum(eleve.notes)

print(f"La moyenne est de : {moyenne/len(eleves*3)} et les notes vont de {note_min} à {note_max}")

ValueError: invalid literal for int() with base 10: ''

## Exercice 5

Lire et écrire dans un fichier

1\. Fichiers


In [ ]:
# écrire dans un fichier
message = "Bonjour le monde"
with open("bonjour.txt", "w") as file:
    file.write(message)
file.close()

In [ ]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

In [ ]:
# écrire dans un fichier
message1 = "Bonjour le monde"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [ ]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

In [ ]:
# Rédaction dans un fichier en utilisant le caractère de nouvelle ligne
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

2\. readline()

Cette fonction peut être utilisée pour lire un fichier ligne par ligne et non le contenu complet en un seul appel comme read()

In [ ]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [ ]:
with open("bonjour.txt", "r") as file:
    text = file.readline()
    print(text)
file.close()

In [ ]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python\n"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [ ]:
with open("bonjour.txt", "r") as file:
    for line in file:
        print(line)
file.close()

**Question:** Copiez un fichier HTML dans votre répertoire. Ecrire un programme
en Python pour obtenir les valeurs suivantes :

- nombre de caractères dans le fichier HTML
- nombre de lignes dans le fichier HTML
- nombre de mots dans le fichier HTML
- les vingt premiers mots du fichier HTML
- des mots distincts dans le fichier HTML



In [19]:
path = "./text.txt"

file = open(path, "r")
text = file.read()

nbr_char = len(text)
print(nbr_char)

nbr_ligne = len(text.splitlines())
print(nbr_ligne)

nbr_words = len(text.split())
print(nbr_words)

print(text.split()[:20])

print(set(text.split()))

file.close()

795
1
117
['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetur', 'adipiscing', 'elit.', 'Quisque', 'hendrerit', 'diam', 'a', 'neque', 'ullamcorper', 'commodo.', 'Quisque', 'ac', 'mi', 'sit', 'amet']
{'accumsan.', 'Nulla', 'lectus', 'risus.', 'dui', 'ipsum', 'vehicula', 'hac', 'sodales', 'ac', 'ex', 'pulvinar', 'quis', 'dolor', 'tincidunt.', 'nec,', 'ornare', 'justo.', 'Fusce', 'In', 'condimentum', 'vitae', 'neque', 'lacus', 'sem,', 'tincidunt,', 'congue', 'nunc,', 'nec', 'elit.', 'arcu', 'egestas', 'cursus', 'adipiscing', 'pellentesque', 'et', 'Suspendisse', 'egestas.', 'rhoncus.', 'pretium', 'amet', 'diam', 'nunc.', 'eleifend', 'id', 'platea', 'Quisque', 'blandit', 'commodo.', 'at', 'Nullam', 'mi', 'habitasse', 'nisl', 'rutrum', 'Morbi', 'elementum', 'orci', 'diam.', 'porta.', 'hendrerit', 'molestie', 'augue', 'Lorem', 'dui,', 'ullamcorper', 'felis.', 'ligula,', 'rhoncus', 'hendrerit.', 'tincidunt', 'dictumst.', 'dignissim', 'Curabitur', 'posuere', 'consectetur', 'leo', 'Sed', 'si

**Question:** Copier le CSV
du fichier population.csv du dossier **data**. Le fichier contient les valeurs de population entre
1901 et 2016. Écrivez un programme en Python pour obtenir la valeur maximale.

- la valeur maximale de la population
- la valeur minimale de la population


In [21]:
import csv

path = "./population.csv"

# Print le min et le max de la première colonne (séparé par des virgules), avec les valeurs en 2e colonne correspondantes
file = open(path, "r")
reader = csv.reader(file, delimiter=",")

# On saute la première ligne
next(reader)

min = 0
max = 0
for row in reader:
    if min == 0 or int(row[1]) < min:
        min = int(row[1])
        min_year = row[0]
    if max == 0 or int(row[1]) > max:
        max = int(row[1])
        max_year = row[0]

print(f"Le min est de {min} en {min_year} et le max est de {max} en {max_year}")

Le min est de 40681000 en 1901 et le max est de 66632870 en 2016


## Numpy

In [2]:
import numpy as np

### Les opérations sur les matrices

In [3]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

In [4]:
c1 = np.add(a1, b1)
print(c1)

[ 6  8 10 12]


In [5]:
c1 = np.subtract(a1, b1)
print(c1)

[-4 -4 -4 -4]


In [ ]:
c1 = np.multiply(a1, b1)
print(c1)

In [6]:
c1 = np.multiply(4, b1)
print(c1)

[20 24 28 32]


In [7]:
c1 = np.dot(a1, b1)
print(c1)

70


In [ ]:
c1 = np.dot(5, b1)
print(c1)

In [ ]:
b1 = [5, 6, 7, 8]
c1 = np.dot(a1, b1)
print(c)

In [8]:
a1 = [1, 2]
moyen = np.average(a1)
print(moyen)

1.5


### Tranposition matricielle

In [9]:
b1 = [[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
print(b1)
b1 = np.array(b1)
print(b1.T)

[[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]
 [9 5]]


### Séparer une matrice en deux, horizontalement et verticalement

In [10]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.hsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [ ]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.vsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

### Les opérations sur les matrices bidimensionnelles

In [ ]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]

In [ ]:
c2 = np.add(a2, b2)
print(c2)

In [ ]:
c2 = np.subtract(a2, b2)
print(c2)

In [ ]:
c2 = np.multiply(a2, b2)
print(c2)

In [ ]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
a2 = np.array(a2)
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]
b2 = np.array(b2)
c2 = np.dot(a2, b2.T)
print(c2)

### Redéfinir une matrice

In [ ]:
b2.reshape(4, 2)
print(b2)

### Créer des matrices avec des nombres aléatoires

In [ ]:
a = np.random.rand()
print(a)

In [ ]:
a = np.random.rand(1)
print(a)

In [ ]:
a = np.random.rand(2, 5)
print(a)

In [ ]:
a = np.random.rand(2, 3, 3)
print(a)

In [ ]:
a = np.zeros(1)
print(a)

In [ ]:
a = np.zeros(1, dtype=int)
print(a)

In [ ]:
a = np.zeros((2, 5), dtype=int)
print(a)

### Quelques fonctions pour travailler avec des listes

In [ ]:
a = [12, 13, 14, 15]
a_reverse = reversed(a)

for num in a_reverse:
    print(num)

In [1]:
jours = ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi"]
jours_num = list(enumerate(jours))
print(jours_num)

jours_num = list(enumerate(jours, start=1))
print(jours_num)

[(0, 'dimanche'), (1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi')]
[(1, 'dimanche'), (2, 'lundi'), (3, 'mardi'), (4, 'mercredi'), (5, 'jeudi'), (6, 'vendredi')]


In [ ]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

zipped = list(zip(a1, b1))
print(zipped)

In [ ]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

ezipped = list(enumerate(zip(a1, b1)))
print(ezipped)